### ISSUE TITLE
polish the metadata design

### ISSUE THREAD

**Issue by jshawl** [jshawl/gistalt#108]
I feel like the strongest thing on the page is the filename and metadata, which are probably the least important.

![](https://dl.dropbox.com/s/4tzdlbhaqhqha3v/Screenshot%202015-04-14%2023.51.57.png?dl=0)

How do you feel about sidebars?

**Comment by duncangraham** [comment]
I don't think a sidebar is the right solution (mostly since the design started with sidebars abound).

They don't degrade on mobile well, and the single column everywhere is way easier to understand and read visually.

That said, I agree that the current design is no good and should change to highlight the content of the gist, letting the metadata fade into the background more. Renaming and tackling this

**Comment by duncangraham** [comment]
if you're logged in, this is what it looks like
![screen shot 2015-04-17 at 1 53 33 am](https://cloud.githubusercontent.com/assets/865298/7198846/abf11574-e4a4-11e4-96ee-6da527369b0f.png)

if you're shared a gist, you also see the author
![screen shot 2015-04-17 at 1 53 56 am](https://cloud.githubusercontent.com/assets/865298/7198855/bb3f2f8e-e4a4-11e4-8e7b-7625c115cd70.png)

**Comment by duncangraham** [comment]
![screen shot 2015-04-17 at 1 58 28 am](https://cloud.githubusercontent.com/assets/865298/7198932/4a1d04a6-e4a5-11e4-83f8-b7ac9658a3a3.png)

sike the shared page looks like this (im hovering over the filename, which is why you can see the border)
