### ISSUE TITLE
rename to gizd?

### ISSUE THREAD

**Issue by jshawl** [jshawl/gistalt#7]

**Comment by jshawl** [comment]
also gizd.it is available

**Comment by duncangraham** [comment]
or djist?

**Comment by duncangraham** [comment]
gyst, jyzt, jizt, djizt, g!st

**Comment by duncangraham** [comment]
I went for a walking brainstorm and started kicking around names. I think gizt or a variation looks fine in text, but when talking about this, gist and gizt (or any variation) sound the same. I think something more clever would work better. Here is the list of things I thought of (some are really bad, bolded ones are my faves):

Plaigiargist
Exorgist
Gism schism (barf)
Gistonish
Gister jester
Gist quik (bisquick)
**Gistalt**
Alternagist
Legit legist
Magister maGIST maGISTrate
Synergist
Neogist
Gisterical or Gysterical
**Gistopia**

I like gistopia the most, even though it rhymes with dystopia. I like gistalt because of the parallels with gestalt, and the (maybe) more prominent connection with an alternate to gist

whaddya think @jshawl

**Comment by jshawl** [comment]
I _really_ like gistalt

**Comment by jshawl** [comment]
rename and close issue?

**Comment by duncangraham** [comment]
Yea, go for it 

(i don't think i have privileges to)
